// Maps event IDs to their share card image filenames in /public/Share Pics/
// Add new mappings as you add new events and share cards

export const shareCardMap: Record<string, string> = {
  "birth-of-alter-rebbe": "Alter-Rebbe-Birth-Share.png",
  "liberation-alter-rebbe": "Liberation-alter-share.png",
  "birth-of-mitteler-rebbe": "Mitteler-Rebbe-Birth-Share.png",
  "passing-alter-rebbe": "Passing-alter-share.png",
  "rashab-wedding": "Rashab-Wedding-share.png",
  "tanya-published": "Tanya-Share.png",
  "tzemach-tzedek-born": "Tzemach-Tzedek-Birth-Share.png",
  "tzemach-tzedek-nesius": "Tzemach-nesius-share.png",
  "yom-hilula-yisroel-aryeh-leib": "aryeh-leib-share.png",
  "birth-rebbetzin-chana": "chana-birth-share.png",
  "passing-rebbetzin-chana": "chana-pass-share.png",
  "birth-rebbetzin-chaya-mushka": "chaya-mushka-birth-share.png",
  "frierdiker-rebbe-born": "fried-birth-share.png",
  "frierdiker-rebbe-arrested": "fried-arrest-share.png",
  "frierdiker-rebbe-arrives-america": "fried-arrival-share.png",
  "frierdiker-rebbe-nesius": "fried-nesius-share.png",
  "passing-frierdiker-rebbe": "fried-pass-share.png",
  "hei-teves": "hei-teves-share.png",
  "liberation-mitteler-rebbe": "liberation-mitteler-share.png",
  "maharash-born": "maharash-birth-share.png",
  "maharash-nesius-begins": "maharash-nesius-share.png",
  "passing-maharash": "maharash-pass-share.png",
  "mitteler-rebbe-nesius": "nesius-mitteler-share.png",
  "passing-chaya-mushka": "pass-chaya-share.png",
  "passing-rebbe": "pass-rebbe-share.png",
  "passing-mitteler-rebbe": "passing-mittler-share.png",
  "passing-tzemach-tzedek": "passing-tzemach-share.png",
  "rashab-born": "rashab-birth-share.png",
  "passing-rashab": "rashab-passing-share.png",
  "birthday-of-rebbe": "rebbe-birth-share.png",
  "rebbe-rebbetzin-arrive-america": "rebbe-arrive-share.png",
  "yom-hilula-levi-yitzchok": "rebbe-father-pass-share.png",
  "rebbe-heart-attack-recovery": "rebbe-heart-share.png",
  "kabolas-hanisius-rebbe": "rebbe-nesius-share.png",
  "rebbe-rebbetzin-wedding-anniversary": "rebbe-wedding-share.png",
  "passing-rebbetzin-shterna-sara": "shterna-pass-share.png",
  "mivtza-tefillin": "teffilin-share.png",
  "founding-of-tomchei-temimim": "tomchei-share.png",
  "tzemach-tzedek-wedding": "wedding-tzemach-share.png"
};
