export interface TimelineEvent {
  year: string
  hebrewDate: string
  title: string
  description: string
  image: string
  location: string
  tags: string[]
  tachnun?: boolean
  eventId?: string
  imagePosition?: string
  eventType: 'birth' | 'marriage' | 'yom-hilula' | 'nesius' | 'arrested' | 'liberation' | 'arrival' | 'other'
}

export const timelineEvents: TimelineEvent[] = [
  {
    year: "1745",
    hebrewDate: "18 Elul 5505",
    title: "Birth of the Alter Rebbe",
    description: "Rabbi Schneur Zalman of Liadi, founder of Chabad Chassidus, was born in Liozna, Belarus. His revolutionary approach would transform Jewish mysticism into an accessible intellectual system.",
    image: "/alter-rebbe.jpg",
    location: "Liozna, Belarus",
    tags: ["Alter Rebbe"],
    tachnun: true,
    eventId: "birth-of-alter-rebbe",
    eventType: "birth",
  },
  {
    year: "1773",
    hebrewDate: "9 Kislev 5534",
    title: "Birth of the Mitteler Rebbe",
    description: "Birth of Rabbi DovBer Schneuri, the Mitteler Rebbe, second Rebbe of Chabad. He was known for his deep, detailed Chassidic teachings that expanded on his father's works.",
  image: "/mittler-rebbe-9-kislev-pic.jpg",
    location: "Liozna, Belarus",
    tags: ["Mitteler Rebbe"],
    tachnun: true,
    eventId: "birth-of-mitteler-rebbe",
    eventType: "birth",
  },
  {
    year: "1789",
    hebrewDate: "18 Elul 5549",
    title: "Birth of the Tzemach Tzedek",
    description: "Birth of Rabbi Menachem Mendel Schneersohn, the Tzemach Tzedek, third Lubavitcher Rebbe. He became known for his broad Torah scholarship and leadership that strengthened Chabad.",
    image: "/tzemach-born.jpg",
    location: "Liozna, Belarus",
    tags: ["Tzemach Tzedek"],
    tachnun: true,
    eventId: "tzemach-tzedek-born",
    eventType: "birth",
  },
  {
    year: "1796",
    hebrewDate: "20 Kislev 5557",
    title: "Tanya Published",
    description: "The first edition of the Tanya, the foundational text of Chabad philosophy, was printed in Slavuta. This seminal work bridges Kabbalah and daily life, offering profound insights into the human soul.",
    image: "/tanya-2.jpg",
    location: "Slavuta, Ukraine",
    tags: ["Alter Rebbe"],
    tachnun: true,
    eventId: "tanya-published",
    eventType: "other",
  },
  {
    year: "1798",
    hebrewDate: "19 Kislev 5559",
    title: "Liberation of the Alter Rebbe",
    description: "Release of Rabbi Schneur Zalman of Liadi, the Alter Rebbe, from imprisonment in S. Petersburg after being falsely accused by the Russian authorities. His liberation is celebrated in Chabad as the “Rosh Hashanah of Chassidus,” symbolizing the vindication and renewed spread of Chassidic teachings.",
    image: "/alter-rebbe-lib-final.jpeg",
    imagePosition: "center 75%",
    location: "S. Petersburg, Russia",
    tags: ["Alter Rebbe"],
    tachnun: false,
    eventId: "liberation-alter-rebbe",
    eventType: "liberation",
  },
  {
    year: "1812",
    hebrewDate: "24 Teves 5573",
    title: "Yom Hilula of the Alter Rebbe",
    description: "Chassidim commemorate the passing of Rabbi Schneur Zalman of Liadi, founder of Chabad and author of the Tanya. The day is observed through reflection on his life's mission and renewed dedication.",
    image: "/alter-rebbe.jpg",
    location: "Piyena, Russia",
    tags: ["Alter Rebbe"],
    tachnun: true,
    eventId: "passing-alter-rebbe",
    eventType: "yom-hilula",
  },
  {
    year: "1803",
    hebrewDate: "5 Kislev 5564",
    title: "Wedding of the Tzemach Tzedek and Rebbetzin Chaya Mushka",
    description: "Marriage of Rabbi Menachem Mendel Schneersohn (the Tzemach Tzedek) to Rebbetzin Chaya Mushka, daughter of the Mitteler Rebbe.",
    image: "/chuppah.jpg",
    location: "Lubavitch, Russia",
    tags: ["Tzemach Tzedek"],
    tachnun: true,
    eventId: "tzemach-tzedek-wedding",
    eventType: "marriage",
  },
  {
    year: "1812",
    hebrewDate: "25 Teves 5573",
    title: "Mitteler Rebbe's Nesius Begins",
    description: "Rabbi DovBer Schneuri assumed leadership of Chabad following his father's passing. His nesius was defined by deep expansion of Chassidus and establishment of Lubavitch as the movement's center.",
     image: "/mittler-rebbe-9-kislev-pic.jpg",
    location: "Lubavitch, Russia",
    tags: ["Mitteler Rebbe"],
    tachnun: true,
    eventId: "mitteler-rebbe-nesius",
    eventType: "nesius",
  },
  {
    year: "1826",
    hebrewDate: "10 Kislev 5587",
    title: "Chag Hageulah of the Mitteler Rebbe",
    description: "Release of Rabbi DovBer Schneuri from imprisonment in Vitebsk after false accusations. His liberation is celebrated in Chabad as Yom HaGeulah, a day of redemption and vindication.",
    image: "/yudkislev.jpg",
    location: "Vitebsk, Russia",
    tags: ["Mitteler Rebbe"],
    tachnun: false,
    eventId: "mitteler-rebbe-liberation",
    eventType: "other",
  },
  {
    year: "1827",
    hebrewDate: "9 Kislev 5588",
    title: "Yom Hilula of Mitteler Rebbe",
    description: "Passing of Rabbi DovBer Schneuri, the Mitteler Rebbe, second Rebbe of Chabad. He passed away on his birthday, making 9 Kislev both his birth and yahrzeit.",
  image: "/mitteler-pass.jpeg",
    location: "Niezhin, Russia",
    tags: ["Mitteler Rebbe"],
    eventId: "passing-mitteler-rebbe",
    eventType: "yom-hilula",
  },
  {
    year: "1829",
    hebrewDate: "3 Sivan 5589",
    title: "Nesius of Tzemach Tzedek Begins",
    description: "Rabbi Menachem Mendel Schneersohn, the Tzemach Tzedek, assumed leadership of Chabad after the Mitteler Rebbe's passing. His nesius was defined by exceptional Torah scholarship and strengthening Jewish life.",
    image: "/tzemach-2.jpg",
    location: "Lubavitch, Russia",
    tags: ["Tzemach Tzedek"],
    tachnun: true,
    eventId: "tzemach-tzedek-nesius",
    eventType: "other",
  },
  {
    year: "1834",
    hebrewDate: "2 Iyar 5594",
    title: "Birth of the Rebbe Maharash",
    description: "Birth of Rabbi Shmuel Schneersohn, the Rebbe Maharash, the fourth Lubavitcher Rebbe. He was known for exceptional depth in Chassidus and leadership during difficult times for Russian Jewry.",
    image: "/maharash-born.jpg",
    location: "Lubavitch, Russia",
    tags: ["Rebbe Maharash"],
    tachnun: true,
    eventId: "maharash-born",
    eventType: "birth",
  },
  {
    year: "1860",
    hebrewDate: "20 Cheshvan 5621",
    title: "Birthday of the Rebbe Rashab",
    description: "Birth of Rabbi Sholom DovBer Schneersohn, the Rebbe Rashab, fifth Lubavitcher Rebbe. He founded the Tomchei Temimim Yeshiva and shaped generations of Chabad students.",
    image: "/rashab.jpg",
    location: "Lubavitch, Russia",
    tags: ["Rebbe Rashab"],
    tachnun: true,
    eventId: "birthday-rebbe-rashab",
    eventType: "birth",
  },
  {
    year: "1875",
    hebrewDate: "11 Elul 5635",
    title: "Marriage of the Rebbe Rashab to Rebbetzin Shterna Sara",
    description: "Wedding of Rabbi Sholom DovBer Schneersohn (the Rebbe Rashab) to Rebbetzin Shterna Sara.",
    image: "/rashab-wedding.jpg",
    location: "Lubavitch, Russia",
    tags: ["Rebbe Rashab"],
    tachnun: false,
    eventId: "rebbe-rashab-wedding",
    eventType: "marriage",
  },
  {
    year: "1880",
    hebrewDate: "28 Tevet 5640",
    title: "Birth of Rebbetzin Chana",
    description: "Birth of Rebbetzin Chana Schneerson, mother of the Lubavitcher Rebbe.",
    image: "/reb-chana.webp",
    location: "Nikolayev, Ukraine",
    tags: [],
    tachnun: false,
    eventId: "birth-rebbetzin-chana",
    eventType: "birth",
  },
  {
    year: "1866",
    hebrewDate: "13 Nisan 5626",
    title: "Passing of the Tzemach Tzedek",
    description: "Rabbi Menachem Mendel Schneersohn, the third Chabad Rebbe, passed away after expanding Chabad's influence and authoring thousands of responsa and Chassidic discourses.",
    image: "/tzemach-2.jpg",
    location: "Lubavitch, Russia",
    tags: ["Tzemach Tzedek"],
    tachnun: false,
    eventId: "passing-tzemach-tzedek",
    eventType: "yom-hilula",
  },
  {
    year: "1866",
    hebrewDate: "1 Nisan 5626",
    title: "Rebbe Maharash's Nesius Begins",
    description: "Rabbi Shmuel Schneersohn assumed leadership of Chabad-Lubavitch. His nesius emphasized the principle of 'L'chatchila ariber'—confronting obstacles head-on rather than circumventing them.",
    image: "/maharash-2.jpg",
    location: "Lubavitch, Russia",
    tags: ["Rebbe Maharash"],
    tachnun: false,
    eventType: "nesius",
    eventId: "maharash-nesius-begins",
  },
  {
    year: "1880",
    hebrewDate: "12 Tamuz 5640",
    title: "Frierdiker Rebbe Born",
    description: "Birth of Rabbi Yosef Yitzchak Schneersohn, the Frierdiker Rebbe, the sixth Lubavitcher Rebbe. He later became a heroic leader of Soviet Jewry, strengthening Torah life under extreme persecution, and ultimately rebuilt Chabad in the United States, laying the foundation for its global revival.",
    image: "/fried-rebbe.jpg",
    location: "Lubavitch, Russia",
    tags: ["Frierdiker Rebbe"],
    tachnun: false,
    eventId: "birth-of-frierdiker-rebbe",
    eventType: "birth",
  },
  {
    year: "1882",
    hebrewDate: "13 Tishrei 5643",
    title: "Yom Hilula of the Rebbe Maharash",
    description: "Passing of Rabbi Shmuel Schneersohn, the Rebbe Maharash, fourth Lubavitcher Rebbe. Known for “L’chatchila ariber,” he strengthened Jewish life and Torah study in Russia and was succeeded by his son, the Rebbe Rashab.",
    image: "/maharash-pass-3.jpg",
    location: "Lubavitch, Russia",
    tags: ["Rebbe Maharash"],
    tachnun: true,
    eventId: "passing-maharash",
    eventType: "yom-hilula",
  },
  {
    year: "1897",
    hebrewDate: "15 Elul 5657",
    title: "Founding of Tomchei Temimim",
    description: "The Rebbe Rashab established the first Chabad yeshiva in Lubavitch, creating a revolutionary educational institution that combined Talmudic study with Chassidic philosophy.",
    image: "/tomtem.jpg",
    location: "Lubavitch, Russia",
    tags: ["Rebbe Rashab"],
    tachnun: true,
    eventId: "founding-of-tomchei-temimim",
    eventType: "other",
  },
  {
    year: "1901",
    hebrewDate: "25 Adar 5661",
    title: "Birthday of Rebbetzin Chaya Mushka",
    description: "Birth of Rebbetzin Chaya Mushka Schneerson, later wife of the Lubavitcher Rebbe, known for her humility, devotion, and support of Chabad.",
    image: "/chayamushka.jpg",
    location: "Babinovitch, Russia",
    tags: [],
    tachnun: true,
    eventId: "birthday-rebbetzin-chaya-mushka",
    eventType: "birth",
  },
  {
    year: "1902",
    hebrewDate: "11 Nisan 5662",
    title: "Birthday of the Rebbe",
    description: "Birth of Rabbi Menachem Mendel Schneerson, the Seventh Lubavitcher Rebbe, in Nikolaev, Ukraine. He would later become the leader of Chabad-Lubavitch, transforming it into a global movement through outreach, education, and the Mivtzoim campaigns.",
    image: "/rebbe-birth.webp",
    location: "Nikolayev, Ukraine",
    tags: ["Lubavitcher Rebbe"],
    tachnun: true,
    eventId: "birthday-of-rebbe",
    eventType: "birth",
  },
  {
    year: "1920",
    hebrewDate: "2 Nisan 5680",
    title: "Yom Hilula of the Rebbe Rashab",
    description: "Passing of Rabbi Sholom DovBer Schneersohn, the Rebbe Rashab, fifth Lubavitcher Rebbe. He founded Tomchei Temimim, strengthened Chabad philosophy, and was succeeded by his son-in-law, Rabbi Yosef Yitzchak Schneersohn, the Frierdiker Rebbe.",
    image: "/rashab.jpg",
    location: "Rostov, Russia",
    tags: ["Rebbe Rashab"],
    tachnun: true,
    eventType: "yom-hilula",
  },
  {
    year: "1920",
    hebrewDate: "2 Nisan 5680",
    title: "Frierdiker Rebbe's Nesius Begins",
    description: "The Frierdiker Rebbe, Rabbi Yosef Yitzchak Schneersohn, began his nesius after the Rebbe Rashab’s passing, strengthening underground Torah life and preserving Judaism under Soviet oppression.",
    image: "/fried-rebbe.jpg",
    location: "Rostov, Russia",
    tags: ["Frierdiker Rebbe"],
    tachnun: true,
    eventId: "frierdiker-rebbe-nesius",
    eventType: "nesius",
  },
  {
    year: "1927",
    hebrewDate: "15 Sivan 5687",
    title: "Frierdiker Rebbe is Arrested",
    description: "Arrest of Rabbi Yosef Yitzchak Schneersohn by Soviet authorities for sustaining Jewish education and observance. He was later released, becoming a beacon of resistance against Soviet persecution.",
    image: "/fried-rebbe-released.jpg",
    location: "Leningrad, Soviet Union",
    tags: ["Frierdiker Rebbe"],
    tachnun: true,
    eventId: "frierdiker-rebbe-arrested",
    eventType: "arrested",
  },
  {
    year: "1928",
    hebrewDate: "14 Kislev 5689",
    title: "Wedding Anniversary of the Rebbe and Rebbetzin",
    description: "Marriage of Rabbi Menachem Mendel Schneerson to Chaya Mushka in Warsaw. This union secured Chabad's leadership continuity for future generations.",
    image: "/rebbe-wedding.png",
    location: "Warsaw, Poland",
    tags: ["Lubavitcher Rebbe"],
    tachnun: true,
    eventId: "rebbe-rebbetzin-wedding-anniversary",
    eventType: "marriage",
  },
  {
    year: "1940",
    hebrewDate: "9 Adar 5700",
    title: "Frierdiker Rebbe's Arrival In the United States",
    description: "Arrival of Rabbi Yosef Yitzchak Schneersohn, the Frierdiker Rebbe, in Brooklyn, New York, beginning a new era for Chabad in America.",
    image: "/fried-rebbe-usa.jpg",
    location: "New York, USA",
    tags: ["Frierdiker Rebbe"],
    tachnun: true,
    eventId: "frierdiker-rebbe-arrives-america",
    eventType: "arrival",
  },
  {
    year: "1941",
    hebrewDate: "28 Sivan 5701",
    title: "Rebbe and Rebbetzin Arrive in the United States",
    description: "The Rebbe and Rebbetzin arrive safely in the United States, escaping war-torn Europe. This marked a turning point in Chabad history and the beginning of its global expansion.",
    image: "/Rebbe-Usa.jpg",
    location: "New York, USA",
    tags: ["Lubavitcher Rebbe"],
    tachnun: true,
    eventId: "rebbe-rebbetzin-arrive-america",
    eventType: "other",
  },
  {
    year: "1944",
    hebrewDate: "20 Av 5704",
    title: "Yom Hilula of Rabbi Levi Yitzchok, the Rebbe's Father",
    description: "Yom Hilula of Rabbi Levi Yitzchok Schneerson, father of the Rebbe. A towering Kabbalist and Rav of Dnepropetrovsk, he endured Soviet persecution and passed away in exile in Kazakhstan.",
    image: "/rebbe-father.jpg",
    location: "Alma-Ata, Kazakhstan",
    tags: [],
    tachnun: true,
    eventId: "yom-hilula-levi-yitzchok",
    eventType: "yom-hilula",
  },
  {
    year: "1942",
    hebrewDate: "13 Shevat 5702",
    title: "Passing of Rebbetzin Shterna Sara",
    description: "Passing of Rebbetzin Shterna Sara, wife of the Rebbe Rashab and mother of the Frierdiker Rebbe.",
    image: "/shterna.jpg",
    location: "Riga, Latvia",
    tags: [],
    tachnun: false,
    eventId: "passing-rebbetzin-shterna-sara",
    eventType: "yom-hilula",
  },
  {    year: "1950",
    hebrewDate: "10 Shevat 5710",
    title: "Yom Hilula of the Frierdiker Rebbe",
    description: "Passing of Rabbi Yosef Yitzchak Schneersohn, the Sixth Lubavitcher Rebbe, who guided Chabad through Soviet persecution and World War II. His passing marked the transition to his son-in-law, Rabbi Menachem Mendel Schneerson, as the seventh Rebbe.",
    image: "/fried-rebbe.jpg",
    location: "Brooklyn, New York",
    tags: ["Frierdiker Rebbe"],
    tachnun: true,
    eventId: "yom-hilula-frierdiker-rebbe",
    eventType: "yom-hilula",
  },
  {
    year: "1951",
    hebrewDate: "10 Shevat 5711",
    title: "The Rebbe Accepts the Nesius",
    description: "Rabbi Menachem Mendel Schneerson assumes leadership as the Seventh Lubavitcher Rebbe. His leadership would profoundly transform Chabad worldwide through outreach, education, and the global Mivtzoim campaigns.",
    image: "/10shavt2.jpg",
    location: "Brooklyn, New York",
    tags: ["Lubavitcher Rebbe"],
    tachnun: false,
    eventId: "kabolas-hanisius-rebbe",
    eventType: "nesius",
  },
  {
    year: "1952",
    hebrewDate: "13, Iyar 5712",
      title: "Yom Hilula Reb Yisroel Aryeh Leib, the Rebbe’s Brother",
    description: "Passing of Reb Yisroel Aryeh Leib Schneerson, the Rebbe's younger brother and a brilliant Torah scholar in England. The Rebbe later dedicated several talks and letters in his memory.",
image: "/yis-ar-grave.jpg",
    location: "Liverpool England.",
    tags: [],
    tachnun: false,
    eventId: "yom-hilula-yisroel-aryeh-leib",
    eventType: "yom-hilula",
  },
  {
    year: "1964",
    hebrewDate: "6 Tishrei 5725",
    title: "Yom Hilula of the Rebbe's Mother, Rebbetzin Chana",
    description: "Rebbetzin Chana Schneerson passed away at age 84, a woman of deep faith and quiet heroism. She was married to Rabbi Levi Yitzchak Schneerson, a renowned kabbalist and chief rabbi of Yekaterinoslav.",
    image: "/reb-chana.webp",
    location: "Brooklyn, New York",
    tags: [],
    tachnun: false,
    eventId: "passing-rebbetzin-chana",
    eventType: "yom-hilula",
  },
  {
    year: "1967",
    hebrewDate: "28 Iyar 5727",
    title: "The Rebbe Starts Mivtza Tefillin",
    description: "The Rebbe launches Mivtza Tefillin during the Six-Day War, encouraging Jews worldwide to put on tefillin daily. This marked the beginning of the Rebbe's global Mivtzoim campaigns, which inspired millions.",
image: "/mivtza.jpg",
    location: "Brooklyn, New York",
    tags: ["Lubavitcher Rebbe"],
    tachnun: true,
    eventId: "mivtza-tefillin",
    eventType: "other",
  },
  {
    year: "1977",
    hebrewDate: "1 Kislev 5738",
    title: "The Rebbe Recovers from his Heart Attack",
    description: "The Rebbe returns home after a severe heart attack on Shemini Atzeres, with his recovery seen as a great miracle. Rosh Chodesh Kislev is celebrated in Chabad as Yom Simchah, marking his return to public life.",
    image: "/rbbe-heart-2.jpg",
    imagePosition: "70% center",
    location: "Brooklyn, New York",
    tags: ["Lubavitcher Rebbe"],
    tachnun: true,
    eventId: "rebbe-heart-attack-recovery",
    eventType: "other",
  },
  {
    year: "1987",
    hebrewDate: "5 Teves 5747",
    title: "Didan Notzach of the Seforim",
    description: "The court rules in favor of Chabad in a lawsuit over ownership of the Rebbeim's manuscripts and rare books. The decision ensures these sacred texts remain Chabad's property for continued study and publication.",
    image: "/hei-teves.jpg",
    location: "Brooklyn, New York",
    tags: ["Lubavitcher Rebbe"],
    tachnun: false,
    eventId: "didan-notzach",
    eventType: "other",
  },
  {
    year: "1988",
    hebrewDate: "22 Shevat 5748",
    title: "Yom Hilula of Rebbetzin Chaya Mushka",
    description: "Passing of Rebbetzin Chaya Mushka Schneerson, wife of the Seventh Lubavitcher Rebbe, revered for her humility and dedication. Her memory is honored through Torah study and dedication to Chabad institutions.",
    image: "/chayamushka.jpg",
    location: "Brooklyn, New York",
    tags: [],
    tachnun: true,
    eventId: "passing-rebbetzin-chaya-mushka",
    eventType: "yom-hilula",
  },
  {
    year: "1994",
    hebrewDate: "3 Tamuz 5754",
    title: "Lubavitcher Rebbe Passes Away",
    description: "The Lubavitcher Rebbe passed away, leaving behind a legacy of thousands of Chabad centers worldwide and millions of lives touched by his teachings and vision.",
    image: "/ohel.jpg",
    location: "Brooklyn, New York",
    tags: ["Lubavitcher Rebbe"],
    tachnun: true,
    eventId: "lubavitcher-rebbe-passes-away",
    eventType: "other",
  },
  {
    year: "2026",
    hebrewDate: "Today",
    title: "Chabad in 100+ Countries",
    description: "Chabad-Lubavitch operates over 5,000 institutions worldwide, serving Jewish communities in over 100 countries. The Rebbe's vision of spreading light and goodness continues to flourish globally.",
    image: "/kinus2025.jpg",
    location: "Worldwide",
    tags: [],
    eventType: "other",
  },
]

export const quotes = [
  "One good deed can tip the scale of the world toward good.",
  "A little bit of light dispels a lot of darkness.",
  "The purpose of creation is to make a dwelling place for G-d in the lower worlds.",
  "Every person has the ability to change the world.",
  "Think good, and it will be good.",
  "We are all one body, one soul.", 
]

export const rebbeNames = [
  "Alter Rebbe",
  "Mitteler Rebbe",
  "Tzemach Tzedek",
  "Rebbe Maharash",
  "Rebbe Rashab",
  "Frierdiker Rebbe",
  "Lubavitcher Rebbe",
]
export const rebbeNiggunim: { [key: string]: string } = {
  "Alter Rebbe": "/alter-rebbe-niggun.mp3",
  "Mitteler Rebbe": "/mitteler-niggun.mp3",
  "Tzemach Tzedek": "/tzemach-niggun.mp3",
  "Rebbe Maharash": "/maharash-niggun.mp3",
  "Rebbe Rashab": "/rashab-niggun.mp3",
  "Frierdiker Rebbe": "/fried-niggun.mp3",
  "Lubavitcher Rebbe": "/Tzama.mp3",
}
